
atmosphere-grid:
  bottom: 0.0 # cm
  top: 1.0e7 # cm
  number-of-layers: 100

planet:
  planet-mass: 5.972e27 # g
  planet-radius: 6.371e8 # cm
  surface-albedo: 0.25
  solar-zenith-angle: 60.0
  hydrogen-escape:
    type: diffusion limited
  water:
    fix-water-in-troposphere: false
    gas-rainout: true
    rainfall-rate: 1
    tropopause-altitude: 1.25e6
    water-condensation: false
  
particles:
- {name: H2Oaer, RH-condensation: 0.8} # water vapor set to 80% relative humidity

boundary-conditions:
# Radicals like O, OH, HO2, CH3, HCO, HNO at 1 cm/s
- name: O
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: flux, flux: 0.0}
- name: OH
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: flux, flux: 0.0}
- name: HO2
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: flux, flux: 0.0}
- name: CH3
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: flux, flux: 0.0}
- name: HCO
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: flux, flux: 0.0}
- name: HNO
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: flux, flux: 0.0}

# H2O2, H2CO at 0.2 cm/s
- name: H2O2
  lower-boundary: {type: vdep, vdep: 0.2}
  upper-boundary: {type: flux, flux: 0.0}
- name: H2CO
  lower-boundary: {type: vdep, vdep: 0.2}
  upper-boundary: {type: flux, flux: 0.0}

# CO at 2E-6 cm/s
- name: CO
  lower-boundary: {type: vdep, vdep: 2e-6}
  upper-boundary: {type: flux, flux: 0.0}

# H2 at 1E11 /cm2/s
- name: H2
  lower-boundary: {type: flux, flux: 1e11}
  upper-boundary: {type: veff, veff: 0.0}

# CH4 at 1.E8 /cm2/s
- name: CH4
  lower-boundary: {type: flux, flux: 1e8}
  upper-boundary: {type: veff, veff: 0.0}

# lightning flux of NO in the troposphere of 5E8 /cm2/s
- name: "NO"
  lower-boundary: {type: flux, flux: 5e8}
  upper-boundary: {type: veff, veff: 0.0}

# Bulk composition: 20% CO2, 80% N2
- name: CO2
  lower-boundary: {type: press, press: 0.2e6}
  upper-boundary: {type: veff, veff: 0.0}
- name: N2
  lower-boundary: {type: press, press: 0.8e6}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2O # need H2O as well
  lower-boundary: {type: press, press: 270e6}
  upper-boundary: {type: veff, veff: 0.0}