
atmosphere-grid:
  number-of-layers: 100
  
planet:
  planet-mass: 5.972e27
  planet-radius: 6.371e8
  number-of-zenith-angles: 4
  surface-albedo: 0.2
  
optical-properties:
  ir:
    k-method: RandomOverlapResortRebin
    number-of-bins: 32
    opacities:
      k-distributions: [H2O, CO2, CH4]
      CIA: [CH4-CH4, CO2-CH4, CO2-CO2, CO2-H2, H2-CH4, H2-H2, H2O-H2O, H2O-N2, N2-H2, N2-N2]
      rayleigh: true
  solar:
    k-method: RandomOverlapResortRebin
    number-of-bins: 32
    opacities:
      k-distributions: [H2O, CO2, CH4]
      CIA: [CH4-CH4, CO2-CH4, CO2-CO2, CO2-H2, H2-CH4, H2-H2, H2O-H2O, H2O-N2, N2-H2, N2-N2]
      rayleigh: true
      photolysis-xs: true  
