
atmosphere-grid:
  number-of-layers: 50
  
planet:
  planet-mass: 5.972e27
  planet-radius: 6.371e8
  number-of-zenith-angles: 4
  surface-albedo: 0.2
  
optical-properties:
  ir:
    k-method: RandomOverlapResortRebin
    opacities: {k-distributions: on, CIA: on, rayleigh: on, photolysis-xs: on}
  solar:
    k-method: RandomOverlapResortRebin
    opacities: {k-distributions: on, CIA: on, rayleigh: on, photolysis-xs: on}
