
atmosphere-grid:
  bottom: 0.0 # cm
  top: 1.0e7 # cm
  number-of-layers: 100

planet:
  planet-mass: 5.972e27 # g
  planet-radius: 6.371e8 # cm
  surface-albedo: 0.2 # cm
  solar-zenith-angle: 60.0
  hydrogen-escape:
    type: diffusion limited
  water:
    fix-water-in-troposphere: false 
    gas-rainout: true
    rainfall-rate: 1
    tropopause-altitude: 1.1e6
    water-condensation: false

particles:
- {name: H2Oaer, RH-condensation: 0.5}  

boundary-conditions:
- name: H2O
  lower-boundary: {type: press, press: 270e6}
  upper-boundary: {type: veff, veff: 0.0}
- name: N2
  lower-boundary: {type: press, press: 0.7e6}
  upper-boundary: {type: veff, veff: 0.0}
- name: CO2
  # From Krissansen-Totton et al. (2018), PNAS, Fig. 3
  # for CO2 at 3.8 Ga
  lower-boundary: {type: press, press: 0.3e6}
  upper-boundary: {type: veff, veff: 0.0}
- name: CO
  # vdep from (Kharecha et al. 2004) for CO hydrolysis in ocean.
  # The flux is from Archean+haze template in the VPL Atmos code.
  lower-boundary: {type: vdep + dist flux, vdep: 1.0e-8, flux: 1.0e9, height: -1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2
  # From Archean+haze template in the VPL Atmos code.
  lower-boundary: {type: flux, flux: 1.0e10}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCN
  # Emulates HCN hydrolysis in the ocean (Wogan et al. 2023)
  lower-boundary: {type: vdep, vdep: 0.007}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCCCN
  # Assumed to be the same as HCN
  lower-boundary: {type: vdep, vdep: 0.007}
  upper-boundary: {type: veff, veff: 0.0}

# Boundary conditions copied from the Atmos Archean+haze template
- name: O
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: flux, flux: 0.0}
- name: H
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: OH
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: HO2
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2O2
  lower-boundary: {type: vdep, vdep: 0.2}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCO
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2CO
  lower-boundary: {type: vdep, vdep: 0.2}
  upper-boundary: {type: veff, veff: 0.0}
- name: CH3
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: 'NO'
  lower-boundary: {type: vdep, vdep: 0.0003}
  upper-boundary: {type: veff, veff: 0.0}
- name: NO2
  lower-boundary: {type: vdep, vdep: 0.003}
  upper-boundary: {type: veff, veff: 0.0}
- name: HNO
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: O3
  lower-boundary: {type: vdep, vdep: 0.07}
  upper-boundary: {type: veff, veff: 0.0}
- name: HNO3
  lower-boundary: {type: vdep, vdep: 0.2}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2S
  lower-boundary: {type: vdep + dist flux, vdep: 0.02, flux: 350000000.0, height: -1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: HSO
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2SO4
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: SO2
  lower-boundary: {type: vdep + dist flux, vdep: 1.0, flux: 3500000000.0, height: -1.0}
  upper-boundary: {type: veff, veff: 0.0}

